### ISSUE TITLE
保存图片出错

### ISSUE THREAD

**Issue by skyABB** [Sharpiless/Yolov5-Flask-VUE#14]
Fusing layers... 
D:\soft\ananconda\envs\torch1.12\lib\site-packages\torch\functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\TensorShape.cpp:2895.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
2024-03-24 12:58:22.434146 1.jpg
./tmp/ct/1.jpg
1
Traceback (most recent call last):
  File "D:\soft\ananconda\envs\torch1.12\lib\site-packages\flask\app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "D:\soft\ananconda\envs\torch1.12\lib\site-packages\flask\app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "D:\soft\ananconda\envs\torch1.12\lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\soft\ananconda\envs\torch1.12\lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\soft\ananconda\envs\torch1.12\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\soft\ananconda\envs\torch1.12\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\gjcde\Desktop\Yolov5-Flask-VUE-master\back-end\app.py", line 53, in upload_file
    pid, image_info = core.main.c_main(
  File "c:\Users\gjcde\Desktop\Yolov5-Flask-VUE-master\back-end\core\main.py", line 6, in c_main
    image_info = predict.predict(image_data, model, ext)
  File "c:\Users\gjcde\Desktop\Yolov5-Flask-VUE-master\back-end\core\predict.py", line 12, in predict
    raise Exception('保存图片时出错.Error saving thepicture.')
Exception: 保存图片时出错.Error saving thepicture.

**Comment by xienova** [comment]
# if cv2.imwrite('./tmp/draw/{}.{}'.format(file_name, ext), img_y):
    # raise Exception('保存图片时出错.Error saving thepicture.')

    将上面两句中的if判断去掉试试。 只保留右边这句 cv2.imwrite('./tmp/draw/{}.{}'.format(file_name, ext), img_y)

**Comment by skyABB** [comment]
def predict(dataset, model, ext):
    global img_y
    x = dataset[0].replace('\\', '/')
    file_name = dataset[1]
    # print(x)
    # print(file_name)
    x = cv2.imread(x)
    img_y, image_info = model.detect(x)
    # print(img_y)
    # print('Saving image to:'.format(file_name, ext))
    # if cv2.imwrite('./tmp/draw/{}.{}'.format(file_name, ext), img_y):
    #     raise Exception('保存图片时出错.Error saving thepicture.')
    return image_info
非常感谢，已经解决，希望对后来者有帮助
